In [7]:
from sklearn.datasets import load_iris
 
iris_dataset = load_iris() # 붓꽃 데이터셋을 적재합니다

In [8]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size = 0.2)
# 데이터셋을 랜덤하게 80%의 훈련셋과 20%의 테스트셋으로 분리합니다.

In [9]:
print(X_train)

[[6.3 2.5 5.  1.9]
 [7.4 2.8 6.1 1.9]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [5.4 3.9 1.3 0.4]
 [5.7 2.8 4.5 1.3]
 [6.2 2.9 4.3 1.3]
 [6.1 2.9 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [5.7 2.6 3.5 1. ]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]
 [6.4 3.1 5.5 1.8]
 [5.8 2.7 4.1 1. ]
 [5.7 2.5 5.  2. ]
 [5.7 2.9 4.2 1.3]
 [5.6 2.7 4.2 1.3]
 [4.5 2.3 1.3 0.3]
 [5.  3.  1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [6.9 3.1 5.4 2.1]
 [4.9 3.  1.4 0.2]
 [6.1 2.8 4.7 1.2]
 [5.8 2.7 5.1 1.9]
 [6.9 3.2 5.7 2.3]
 [5.5 3.5 1.3 0.2]
 [7.2 3.  5.8 1.6]
 [5.  3.4 1.5 0.2]
 [6.3 2.9 5.6 1.8]
 [6.  3.4 4.5 1.6]
 [4.6 3.6 1.  0.2]
 [4.9 3.1 1.5 0.1]
 [7.2 3.2 6.  1.8]
 [5.6 2.9 3.6 1.3]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [7.3 2.9 6.3 1.8]
 [6.  2.2 4.  1. ]
 [6.6 3.  4.4 1.4]
 [6.  2.9 4.5 1.5]
 [4.4 3.  1.3 0.2]
 [6.2 2.2 4.5 1.5]
 [5.9 3.  4.2 1.5]
 [6.4 3.2 5.3 2.3]
 [7.2 3.6 6.1 2.5]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.5 1.6 0.6]
 [6.  2.7 5.1 1.6]
 [5.5 2.6 4.4 1.2]
 [5.1 3.4 1.5 0.2]
 [6.2 2.8 4.

In [10]:
print("특성1 범위: ", "[", min(X_train[:, 0]), ",", max(X_train[:, 0]), "]")
print("특성2 범위: ", "[", min(X_train[:, 1]), ",", max(X_train[:, 1]), "]")
print("특성3 범위: ", "[", min(X_train[:, 2]), ",", max(X_train[:, 2]), "]")
print("특성4 범위: ", "[", min(X_train[:, 3]), ",", max(X_train[:, 3]), "]")


특성1 범위:  [ 4.3 , 7.9 ]
특성2 범위:  [ 2.0 , 4.4 ]
특성3 범위:  [ 1.0 , 6.9 ]
특성4 범위:  [ 0.1 , 2.5 ]


In [11]:
from sklearn.preprocessing import StandardScaler
 
sc = StandardScaler()
sc.fit(X_train)
 
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [12]:
print("표준화된 특성1 범위: ", "[", min(X_train_std[:, 0]), ",", max(X_train_std[:, 0]), "]")
print("표준화된 특성2 범위: ", "[", min(X_train_std[:, 1]), ",", max(X_train_std[:, 1]), "]")
print("표준화된 특성3 범위: ", "[", min(X_train_std[:, 2]), ",", max(X_train_std[:, 2]), "]")
print("표준화된 특성4 범위: ", "[", min(X_train_std[:, 3]), ",", max(X_train_std[:, 3]), "]")


표준화된 특성1 범위:  [ -1.8801744737341672 , 2.558270185572716 ]
표준화된 특성2 범위:  [ -2.3319799833170975 , 2.914974979146372 ]
표준화된 특성3 범위:  [ -1.5129512469687252 , 1.8157295574248666 ]
표준화된 특성4 범위:  [ -1.4063347174971899 , 1.7979722337622304 ]


In [13]:
from sklearn.svm import SVC
 
svm_model = SVC(kernel='rbf', C=8, gamma=0.1)
 
svm_model.fit(X_train_std, y_train) # SVM 분류 모델 훈련

SVC(C=8, gamma=0.1)

In [15]:
y_pred = svm_model.predict(X_test_std) # 테스트

In [16]:
print("예측된 라벨:", y_pred)
print("ground-truth 라벨:", y_test)

예측된 라벨: [1 2 0 2 0 2 1 1 0 0 1 2 0 2 1 1 1 2 2 0 2 2 2 2 1 0 1 1 2 0]
ground-truth 라벨: [1 2 0 2 0 2 1 1 0 0 1 2 0 2 1 1 1 2 2 0 2 2 2 2 1 0 1 1 2 0]


In [20]:
import numpy as np

In [21]:
print("prediction accuracy: {:.2f}".format(np.mean(y_pred == y_test))) # 예측 정확도

prediction accuracy: 1.00
